# Generated by Django 2.2.16 on 2021-08-27 10:40

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=8, verbose_name='机房名称')),
                ('address', models.CharField(max_length=32, verbose_name='机房具体地址')),
                ('idctype', models.CharField(max_length=8, verbose_name='机房类型')),
                ('area', models.FloatField(max_length=8, verbose_name='机房面积')),
                ('rack', models.IntegerField(max_length=8, verbose_name='机架数量')),
                ('aircondition', models.IntegerField(max_length=8, verbose_name='空调数量')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('department', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='idc_department', to='permission.Dept', verbose_name='机房所属部门')),
                ('mowner', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc_mowner', to=settings.AUTH_USER_MODEL, verbose_name='总房长')),
                ('owner', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc_owner', to=settings.AUTH_USER_MODEL, verbose_name='房长')),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
            },
        ),
    ]
