# Generated by Django 2.2.16 on 2021-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fzmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='aircondition',
            field=models.IntegerField(verbose_name='空调数量'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='rack',
            field=models.IntegerField(verbose_name='机架数量'),
        ),
    ]
