# Generated by Django 2.2.16 on 2021-08-31 16:47

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fzmm', '0002_auto_20210827_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('starttime', models.DateTimeField(verbose_name='起始时间')),
                ('endtime', models.DateTimeField(verbose_name='截止时间')),
                ('complete', models.BooleanField(verbose_name='是否完成')),
                ('completetime', models.DateTimeField(verbose_name='完成时间')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('idcid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='job_idc', to='fzmm.Idc', verbose_name='所属机房')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_user', to=settings.AUTH_USER_MODEL, verbose_name='总房长')),
            ],
            options={
                'verbose_name': '巡检任务管理',
                'verbose_name_plural': '巡检任务管理',
            },
        ),
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=20, verbose_name='隐患标题')),
                ('context', models.CharField(max_length=128, verbose_name='详细内容')),
                ('complete', models.BooleanField(verbose_name='是否解决')),
                ('step', models.CharField(max_length=128, verbose_name='解决步骤')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('idc', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='danger_idc', to='fzmm.Idc', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '隐患管理',
                'verbose_name_plural': '隐患管理',
            },
        ),
    ]
