# Generated by Django 2.2.16 on 2021-09-23 10:48

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fzmm', '0003_danger_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danger',
            old_name='complete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='danger',
            old_name='step',
            new_name='completestep',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='idcid',
            new_name='completeIdc',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='aircondition',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='area',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='rack',
        ),
        migrations.AddField(
            model_name='danger',
            name='completetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
        migrations.AddField(
            model_name='job',
            name='completeContext',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='完成情况'),
        ),
        migrations.AddField(
            model_name='job',
            name='idctype',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='机房类型'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='巡检任务', max_length=20, unique=True, verbose_name='任务标题'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=8, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='job',
            name='completetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='起始时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_user', to=settings.AUTH_USER_MODEL, verbose_name='房长'),
        ),
        migrations.CreateModel(
            name='IdcEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('totalAirs', models.IntegerField(verbose_name='总空调数')),
                ('usedAirs', models.IntegerField(verbose_name='在用空调数')),
                ('totalPower', models.FloatField(max_length=8, verbose_name='总功率')),
                ('airsPower', models.FloatField(max_length=8, verbose_name='空调功率')),
                ('equipPower', models.FloatField(max_length=8, verbose_name='设备功率')),
                ('idcpve', models.FloatField(max_length=8, verbose_name='能源效率')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('idc', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='idcname_idcenergy', to='fzmm.Idc', verbose_name='机房')),
            ],
            options={
                'verbose_name': '机房能源管理',
                'verbose_name_plural': '机房能源管理',
            },
        ),
        migrations.CreateModel(
            name='IdcArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('area', models.FloatField(max_length=8, verbose_name='机房面积')),
                ('totalRacks', models.IntegerField(verbose_name='总机架数')),
                ('usedRacks', models.IntegerField(verbose_name='在用机架数')),
                ('areaUsed', models.FloatField(max_length=8, verbose_name='空间效率')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('idc', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='idcname_idcarea', to='fzmm.Idc', verbose_name='机房')),
            ],
            options={
                'verbose_name': '机房空间管理',
                'verbose_name_plural': '机房空间管理',
            },
        ),
    ]
